FROM ubuntu:latest

RUN apt update

RUN apt install software-properties-common  net-tools iputils-ping openssh-server sudo -y

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 test

RUN usermod -aG sudo test

RUN service ssh start

RUN apt-add-repository ppa:ansible/ansible

RUN apt install ansible sudo -y

RUN  echo 'test:test' | chpasswd

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]

